//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpockWallet.Localizations {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpockWallet.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address unavailable 的本地化字符串。
        /// </summary>
        internal static string AddressUnavailable {
            get {
                return ResourceManager.GetString("AddressUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure that the address you filled in passed the test 的本地化字符串。
        /// </summary>
        internal static string AddressUnavailableMessage {
            get {
                return ResourceManager.GetString("AddressUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Option 的本地化字符串。
        /// </summary>
        internal static string AdvancedOption {
            get {
                return ResourceManager.GetString("AdvancedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount 的本地化字符串。
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance 的本地化字符串。
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Transfer 的本地化字符串。
        /// </summary>
        internal static string BatchTransfer {
            get {
                return ResourceManager.GetString("BatchTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block 的本地化字符串。
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block Height 的本地化字符串。
        /// </summary>
        internal static string BlockHeight {
            get {
                return ResourceManager.GetString("BlockHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile 的本地化字符串。
        /// </summary>
        internal static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiled Version 的本地化字符串。
        /// </summary>
        internal static string CompiledVersion {
            get {
                return ResourceManager.GetString("CompiledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile Failed 的本地化字符串。
        /// </summary>
        internal static string CompileFailed {
            get {
                return ResourceManager.GetString("CompileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source code or contract name cannot be empty 的本地化字符串。
        /// </summary>
        internal static string CompileFailedMessage {
            get {
                return ResourceManager.GetString("CompileFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected, welcome... 的本地化字符串。
        /// </summary>
        internal static string ConnectedWelcome {
            get {
                return ResourceManager.GetString("ConnectedWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need Node to open RPC 的本地化字符串。
        /// </summary>
        internal static string ConnectNodeSubtitle {
            get {
                return ResourceManager.GetString("ConnectNodeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect To Node 的本地化字符串。
        /// </summary>
        internal static string ConnectToNode {
            get {
                return ResourceManager.GetString("ConnectToNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect to Spock Network 的本地化字符串。
        /// </summary>
        internal static string ConnectToSpock {
            get {
                return ResourceManager.GetString("ConnectToSpock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor Parameters 的本地化字符串。
        /// </summary>
        internal static string ConstructorParams {
            get {
                return ResourceManager.GetString("ConstructorParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contract 的本地化字符串。
        /// </summary>
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contract Name 的本地化字符串。
        /// </summary>
        internal static string ContractName {
            get {
                return ResourceManager.GetString("ContractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contract Name Not Found 的本地化字符串。
        /// </summary>
        internal static string ContractNameNotFound {
            get {
                return ResourceManager.GetString("ContractNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check if the contract name is in the code 的本地化字符串。
        /// </summary>
        internal static string ContractNameNotFoundMessage {
            get {
                return ResourceManager.GetString("ContractNameNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Contract 的本地化字符串。
        /// </summary>
        internal static string ContractSelect {
            get {
                return ResourceManager.GetString("ContractSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied! 的本地化字符串。
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Bytecode 的本地化字符串。
        /// </summary>
        internal static string CopyBytecode {
            get {
                return ResourceManager.GetString("CopyBytecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Error Message 的本地化字符串。
        /// </summary>
        internal static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Wallet 的本地化字符串。
        /// </summary>
        internal static string CreateWallet {
            get {
                return ResourceManager.GetString("CreateWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Your Wallet 的本地化字符串。
        /// </summary>
        internal static string CreateYourWallet {
            get {
                return ResourceManager.GetString("CreateYourWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data (Optional) 的本地化字符串。
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decimals 的本地化字符串。
        /// </summary>
        internal static string Decimals {
            get {
                return ResourceManager.GetString("Decimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Wallet 的本地化字符串。
        /// </summary>
        internal static string DeleteWallet {
            get {
                return ResourceManager.GetString("DeleteWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This address still has {0} SPOK, are you sure you want to delete this address? 的本地化字符串。
        /// </summary>
        internal static string DeleteWalletMessage {
            get {
                return ResourceManager.GetString("DeleteWalletMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy 的本地化字符串。
        /// </summary>
        internal static string Deploy {
            get {
                return ResourceManager.GetString("Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Conteact 的本地化字符串。
        /// </summary>
        internal static string DeployConteact {
            get {
                return ResourceManager.GetString("DeployConteact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment of smart contract requires at least 1000000 SPOK 的本地化字符串。
        /// </summary>
        internal static string DeployLimitTip {
            get {
                return ResourceManager.GetString("DeployLimitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment contract needs to consume 100000 SPOK, are you sure? 的本地化字符串。
        /// </summary>
        internal static string DeployTokenWarning {
            get {
                return ResourceManager.GetString("DeployTokenWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download CSV Template 的本地化字符串。
        /// </summary>
        internal static string DownloadCSVTemplate {
            get {
                return ResourceManager.GetString("DownloadCSVTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter 的本地化字符串。
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Your Mnemonic 的本地化字符串。
        /// </summary>
        internal static string EnterYourMnemonic {
            get {
                return ResourceManager.GetString("EnterYourMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Your Private Key 的本地化字符串。
        /// </summary>
        internal static string EnterYourPrivateKey {
            get {
                return ResourceManager.GetString("EnterYourPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -- All -- 的本地化字符串。
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Address: 的本地化字符串。
        /// </summary>
        internal static string FilterByAddress {
            get {
                return ResourceManager.GetString("FilterByAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Mnemonic 的本地化字符串。
        /// </summary>
        internal static string ForMnemonic {
            get {
                return ResourceManager.GetString("ForMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gas 的本地化字符串。
        /// </summary>
        internal static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gas Price 的本地化字符串。
        /// </summary>
        internal static string GasPrice {
            get {
                return ResourceManager.GetString("GasPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash 的本地化字符串。
        /// </summary>
        internal static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HSITORY 的本地化字符串。
        /// </summary>
        internal static string Hsitory {
            get {
                return ResourceManager.GetString("Hsitory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Wallet 的本地化字符串。
        /// </summary>
        internal static string ImportWallet {
            get {
                return ResourceManager.GetString("ImportWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Your Wallet 的本地化字符串。
        /// </summary>
        internal static string ImportYourWallet {
            get {
                return ResourceManager.GetString("ImportYourWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialization database done... 的本地化字符串。
        /// </summary>
        internal static string InitDbDone {
            get {
                return ResourceManager.GetString("InitDbDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Password Again 的本地化字符串。
        /// </summary>
        internal static string InputPasswordAgain {
            get {
                return ResourceManager.GetString("InputPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input password incorrect. 的本地化字符串。
        /// </summary>
        internal static string InputPasswordIncorrect {
            get {
                return ResourceManager.GetString("InputPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input mnemonic 的本地化字符串。
        /// </summary>
        internal static string InvalidInputMnemonic {
            get {
                return ResourceManager.GetString("InvalidInputMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mnemonic 的本地化字符串。
        /// </summary>
        internal static string Mnemonic {
            get {
                return ResourceManager.GetString("Mnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mnemonic Invalid 的本地化字符串。
        /// </summary>
        internal static string MnemonicInvalid {
            get {
                return ResourceManager.GetString("MnemonicInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Insecurity 的本地化字符串。
        /// </summary>
        internal static string NetworkWarning {
            get {
                return ResourceManager.GetString("NetworkWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are connected to a public node, which will result in network centralization, forgery of transactions and even change of your assets. We recommend that you download the boot and connect to the local node. 的本地化字符串。
        /// </summary>
        internal static string NetworkWarningMessage {
            get {
                return ResourceManager.GetString("NetworkWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Contract Available 的本地化字符串。
        /// </summary>
        internal static string NoContractAvailable {
            get {
                return ResourceManager.GetString("NoContractAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NodeUrl 的本地化字符串。
        /// </summary>
        internal static string NodeUrl {
            get {
                return ResourceManager.GetString("NodeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nonce (Optional) 的本地化字符串。
        /// </summary>
        internal static string Nonce {
            get {
                return ResourceManager.GetString("Nonce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Wallet Available 的本地化字符串。
        /// </summary>
        internal static string NoWalletAvailable {
            get {
                return ResourceManager.GetString("NoWalletAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Browser 的本地化字符串。
        /// </summary>
        internal static string OpenBrowser {
            get {
                return ResourceManager.GetString("OpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password (option) 的本地化字符串。
        /// </summary>
        internal static string OptionPassword {
            get {
                return ResourceManager.GetString("OptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ———————————— or ———————————— 的本地化字符串。
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a password of at least 8 characters. 的本地化字符串。
        /// </summary>
        internal static string PasswordNotStrong {
            get {
                return ResourceManager.GetString("PasswordNotStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entered passwords differ! 的本地化字符串。
        /// </summary>
        internal static string PasswordsDiffer {
            get {
                return ResourceManager.GetString("PasswordsDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter RPC URL addresses 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterRpcUrlAddresses {
            get {
                return ResourceManager.GetString("PleaseEnterRpcUrlAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your URL address 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterURL {
            get {
                return ResourceManager.GetString("PleaseEnterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input your password. 的本地化字符串。
        /// </summary>
        internal static string PleaseInputYourPassword {
            get {
                return ResourceManager.GetString("PleaseInputYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set your password 的本地化字符串。
        /// </summary>
        internal static string PleaseSetYourPassword {
            get {
                return ResourceManager.GetString("PleaseSetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private Key 的本地化字符串。
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private Key unavailable 的本地化字符串。
        /// </summary>
        internal static string PrivateKeyError {
            get {
                return ResourceManager.GetString("PrivateKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive 的本地化字符串。
        /// </summary>
        internal static string Receivables {
            get {
                return ResourceManager.GetString("Receivables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive SPOK 的本地化字符串。
        /// </summary>
        internal static string ReceiveSpok {
            get {
                return ResourceManager.GetString("ReceiveSpok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please report the error message in the text box to us. 的本地化字符串。
        /// </summary>
        internal static string ReportErrorMessage {
            get {
                return ResourceManager.GetString("ReportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPC 的本地化字符串。
        /// </summary>
        internal static string RPC {
            get {
                return ResourceManager.GetString("RPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning：RPC address is not a valid URL address 的本地化字符串。
        /// </summary>
        internal static string RpcStatusInvalidUrl {
            get {
                return ResourceManager.GetString("RpcStatusInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status: test failed 的本地化字符串。
        /// </summary>
        internal static string RpcStatusTestFailed {
            get {
                return ResourceManager.GetString("RpcStatusTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status: testing... 的本地化字符串。
        /// </summary>
        internal static string RpcStatusTesting {
            get {
                return ResourceManager.GetString("RpcStatusTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status: test successful 的本地化字符串。
        /// </summary>
        internal static string RpcStatusTestSuccess {
            get {
                return ResourceManager.GetString("RpcStatusTestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status: waiting test... 的本地化字符串。
        /// </summary>
        internal static string RpcStatusWaitingTest {
            get {
                return ResourceManager.GetString("RpcStatusWaitingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Successful 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please close wallet and restart. 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessfulMessage {
            get {
                return ResourceManager.GetString("SaveSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security 的本地化字符串。
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Assets 的本地化字符串。
        /// </summary>
        internal static string SelectAssets {
            get {
                return ResourceManager.GetString("SelectAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Token 的本地化字符串。
        /// </summary>
        internal static string SelectToken {
            get {
                return ResourceManager.GetString("SelectToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent 的本地化字符串。
        /// </summary>
        internal static string Sended {
            get {
                return ResourceManager.GetString("Sended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send E-mail 的本地化字符串。
        /// </summary>
        internal static string SendEmailReportError {
            get {
                return ResourceManager.GetString("SendEmailReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Failed. 的本地化字符串。
        /// </summary>
        internal static string SendFailed {
            get {
                return ResourceManager.GetString("SendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Transaction 的本地化字符串。
        /// </summary>
        internal static string SendTransaction {
            get {
                return ResourceManager.GetString("SendTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Password 的本地化字符串。
        /// </summary>
        internal static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SETTING 的本地化字符串。
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oops! Something went wrong. 的本地化字符串。
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staking Required 的本地化字符串。
        /// </summary>
        internal static string StakingRequired {
            get {
                return ResourceManager.GetString("StakingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start initialization database... 的本地化字符串。
        /// </summary>
        internal static string StartInitDb {
            get {
                return ResourceManager.GetString("StartInitDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync Failed 的本地化字符串。
        /// </summary>
        internal static string SyncFailed {
            get {
                return ResourceManager.GetString("SyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syncing... 的本地化字符串。
        /// </summary>
        internal static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Synchronized lost blocks, balances and transactions may not be accurate 的本地化字符串。
        /// </summary>
        internal static string SyncTip {
            get {
                return ResourceManager.GetString("SyncTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testing and Saving... 的本地化字符串。
        /// </summary>
        internal static string TestingAndSaving {
            get {
                return ResourceManager.GetString("TestingAndSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To Address 的本地化字符串。
        /// </summary>
        internal static string ToAddress {
            get {
                return ResourceManager.GetString("ToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token Symbol 的本地化字符串。
        /// </summary>
        internal static string TokenSymbol {
            get {
                return ResourceManager.GetString("TokenSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Amount 的本地化字符串。
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Balance 的本地化字符串。
        /// </summary>
        internal static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        internal static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Supply 的本地化字符串。
        /// </summary>
        internal static string TotalSupply {
            get {
                return ResourceManager.GetString("TotalSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        internal static string TxStatusCompleted {
            get {
                return ResourceManager.GetString("TxStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        internal static string TxStatusFailed {
            get {
                return ResourceManager.GetString("TxStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pending 的本地化字符串。
        /// </summary>
        internal static string TxStatusPending {
            get {
                return ResourceManager.GetString("TxStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload CSV File 的本地化字符串。
        /// </summary>
        internal static string UploadCSV {
            get {
                return ResourceManager.GetString("UploadCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Wallet Use Offline Mode 的本地化字符串。
        /// </summary>
        internal static string UseOfflineWallet {
            get {
                return ResourceManager.GetString("UseOfflineWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View in Explorer 的本地化字符串。
        /// </summary>
        internal static string ViewinExplorer {
            get {
                return ResourceManager.GetString("ViewinExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please don&apos;t close the computer until this window closes 的本地化字符串。
        /// </summary>
        internal static string WaitClose {
            get {
                return ResourceManager.GetString("WaitClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has deleted 的本地化字符串。
        /// </summary>
        internal static string WalletHasDeleted {
            get {
                return ResourceManager.GetString("WalletHasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallet Not Found 的本地化字符串。
        /// </summary>
        internal static string WalletNotFound {
            get {
                return ResourceManager.GetString("WalletNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WALLETS 的本地化字符串。
        /// </summary>
        internal static string Wallets {
            get {
                return ResourceManager.GetString("Wallets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Wallet 的本地化字符串。
        /// </summary>
        internal static string WalletSelect {
            get {
                return ResourceManager.GetString("WalletSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallet Version 的本地化字符串。
        /// </summary>
        internal static string WalletVersion {
            get {
                return ResourceManager.GetString("WalletVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I&apos;ve written mnemonims 的本地化字符串。
        /// </summary>
        internal static string WrittenMnemonims {
            get {
                return ResourceManager.GetString("WrittenMnemonims", resourceCulture);
            }
        }
    }
}
